  - name: install microk8s
    become: true
    snap:
      name: microk8s
      classic: true
      
  - name: Add the main user to docker group
    become: true
    user:
      name: "{{ ssh_user }}"
      groups:
        - docker
        - adm
        - sudo
        - microk8s

  - name: reset ssh connection
    meta: reset_connection      
    
  - name: enable basic add-ons for microk8s
    become: true
    become_user: admin
    shell:
      cmd: /snap/bin/microk8s enable dns dashboard storage helm helm3

  - name: starting the proxy in a tmux session
    become: true
    become_user: admin
    shell:
      cmd: tmux ls | grep microk8s-proxy > /dev/null || tmux new -d -s microk8s-proxy /snap/bin/microk8s.kubectl proxy --accept-hosts=.* --address=0.0.0.0
        
  

  